### ISSUE TITLE
Separar archivos de configuración y binarios

### ISSUE THREAD

**Issue by dfbarrero** [munozp/pddl-sim#1]
Crear un directorio config en donde se guarden los archivos de configuración e intermedios (el plan?).

**Comment by munozp** [comment]
Hecho. Se ha creado el directorio config/ donde se aloja la configuración del planificador, así como los archivos de PDDL (dominio, problema y plan).

**Comment by munozp** [comment]
Hecho. Se ha creado un directorio config/ donde se alojan los archivos de PDDL (dominio, problema y plan) y la configuración del planificador.

**Comment by dfbarrero** [comment]
¡Gracias!
